### ISSUE TITLE
Сделать 3 лабу

### ISSUE THREAD

**Issue by OkDenAl** [mevain/assembly-labs#3]
На данный момент. Ком партия Китая требует от пользователя  (ТЗ ПРИКРЕПЛЯЮ)

Техническое задание для выполнения лабораторной работы №3 по ассемблеру

Задача: Написать программу на языке ассемблер для процессора x86, которая бы осуществляла определенные действия.

Требования к программе:
1. Программа должна быть написана на языке ассемблер для процессора x86.
2. Программа должна осуществлять чтение файла в память, обработку данных и запись результата в другой файл.
3. Программа должна содержать комментарии в исходном коде.
4. Программа должна содержать обработку ошибок и вывод сообщений об ошибках в случае необходимости.
5. Программа должна иметь пользовательский интерфейс, где пользователь может выбрать файл для обработки.
6. Программа должна быть устойчива к ошибкам и падениям.

Описание работы программы:
1. Программа должна открывать файл, выбранный пользователем, и считывать его содержимое в память.
2. Программа должна осуществлять обработку данных в памяти в соответствии с заданием лабораторной работы.
3. Программа должна записывать результат обработки в другой файл, который тоже должен быть выбран пользователем.
4. Перед началом работы программа должна проверить корректность выбранных файлов и обработать возможные ошибки.
5. Если возникнут ошибки во время работы программы, то программа должна выводить сообщения об ошибках в пользовательском интерфейсе и прекращать работу.

Критерии оценки:
1. Качество программного кода и оформление исходного текста.
2. Количественные показатели работы программы (скорость работы, использование ресурсов и т.д.).
3. Функциональность программы и соответствие ее требованиям из технического задания.
4. Наличие пользовательского интерфейса и его удобство.

Срок выполнения задания: До конца дня. 17.03.23

Примечание: В случае возникновения затруднений при выполнении лабораторной работы, студент может обратиться к преподавателю для получения дополнительной помощи.

**Comment by MrDzhofik** [comment]
ора такие вещи не мути по-братски
